///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/buffer)
pub fn DataView::buffer(self : DataView) -> ArrayBuffer = "illusory0x0_core_DataView" "get_buffer"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/byteLength)
pub fn DataView::byteLength(self : DataView) -> Int = "illusory0x0_core_DataView" "get_byteLength"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/byteOffset)
pub fn DataView::byteOffset(self : DataView) -> Int = "illusory0x0_core_DataView" "get_byteOffset"
