///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setInt8)
pub fn DataView::setInt8(self : DataView, byteOffset : Int, value : Byte) = "illusory0x0_core_DataView" "setInt8"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setUint8)
pub fn DataView::setUint8(self : DataView, byteOffset : Int, value : Byte) = "illusory0x0_core_DataView" "setUint8"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setInt16)
pub fn DataView::setInt16(
  self : DataView,
  byteOffset : Int,
  value : Int16,
  littleEndian : Bool
) = "illusory0x0_core_DataView" "setInt16"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setUint16)
pub fn DataView::setUint16(
  self : DataView,
  byteOffset : Int,
  value : UInt16,
  littleEndian : Bool
) = "illusory0x0_core_DataView" "setUint16"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setInt32)
pub fn DataView::setInt32(
  self : DataView,
  byteOffset : Int,
  value : Int,
  littleEndian : Bool
) = "illusory0x0_core_DataView" "setInt32"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setUint32)
pub fn DataView::setUint32(
  self : DataView,
  byteOffset : Int,
  value : UInt,
  littleEndian : Bool
) = "illusory0x0_core_DataView" "setUint32"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setFloat32)
pub fn DataView::setFloat32(
  self : DataView,
  byteOffset : Int,
  value : Float,
  littleEndian : Bool
) = "illusory0x0_core_DataView" "setFloat32"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setFloat64)
pub fn DataView::setFloat64(
  self : DataView,
  byteOffset : Int,
  value : Double,
  littleEndian : Bool
) = "illusory0x0_core_DataView" "setFloat64"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setBigInt64)
pub fn DataView::setBigInt64(
  self : DataView,
  byteOffset : Int,
  value : Int64,
  littleEndian : Bool
) = "illusory0x0_core_DataView" "setBigInt64"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setBigUint64)
pub fn DataView::setBigUint64(
  self : DataView,
  byteOffset : Int,
  value : UInt64,
  littleEndian : Bool
) = "illusory0x0_core_DataView" "setBigUint64"
