///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now)
pub fn Date::now() -> Double = "illusory0x0_core_Date" "static_now"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse)
pub fn Date::parse(self : JString) -> Double = "illusory0x0_core_Date" "static_parse"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC)
pub fn Date::utc(
  year : Int,
  monthIndex : Int,
  day : Int,
  hours : Int,
  minutes : Int,
  seconds : Int,
  milliseconds : Int
) -> Date = "illusory0x0_core_Date" "static_UTC"

///|

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toJSON)
pub fn Date::toJSON(self : Date) -> Object = "illusory0x0_core_Date" "toJSON"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString)
pub fn Date::toLocaleString(self : Date) -> JString = "illusory0x0_core_Date" "toLocaleString"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)
pub fn Date::toLocaleDateString(self : Date) -> JString = "illusory0x0_core_Date" "toLocaleDateString"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString)
pub fn Date::toLocaleTimeString(self : Date) -> JString = "illusory0x0_core_Date" "toLocaleTimeString"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toString)
pub fn Date::toString(self : Date) -> JString = "illusory0x0_core_Date" "toString"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toDateString)
pub fn Date::toDateString(self : Date) -> JString = "illusory0x0_core_Date" "toDateString"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toTimeString)
pub fn Date::toTimeString(self : Date) -> JString = "illusory0x0_core_Date" "toTimeString"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
pub fn Date::toISOString(self : Date) -> JString = "illusory0x0_core_Date" "toISOString"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toUTCString)
pub fn Date::toUTCString(self : Date) -> JString = "illusory0x0_core_Date" "toUTCString"
///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toGMTString)
