///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now)
pub fn JDate::now() -> Double = "illusory0x0_core_Date" "static_now"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse)
pub fn JDate::parse(self : JString) -> Double = "illusory0x0_core_Date" "static_parse"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC)
pub fn JDate::utc(
  year : Int,
  monthIndex : Int,
  day : Int,
  hours : Int,
  minutes : Int,
  seconds : Int,
  milliseconds : Int
) -> JDate = "illusory0x0_core_Date" "static_UTC"

///|

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toJSON)
pub fn JDate::toJSON(self : JDate) -> JObject = "illusory0x0_core_Date" "toJSON"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString)
pub fn JDate::toLocaleString(self : JDate) -> JString = "illusory0x0_core_Date" "toLocaleString"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)
pub fn JDate::toLocaleDateString(self : JDate) -> JString = "illusory0x0_core_Date" "toLocaleDateString"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString)
pub fn JDate::toLocaleTimeString(self : JDate) -> JString = "illusory0x0_core_Date" "toLocaleTimeString"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toString)
pub fn JDate::toString(self : JDate) -> JString = "illusory0x0_core_Date" "toString"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toDateString)
pub fn JDate::toDateString(self : JDate) -> JString = "illusory0x0_core_Date" "toDateString"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toTimeString)
pub fn JDate::toTimeString(self : JDate) -> JString = "illusory0x0_core_Date" "toTimeString"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
pub fn JDate::toISOString(self : JDate) -> JString = "illusory0x0_core_Date" "toISOString"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toUTCString)
pub fn JDate::toUTCString(self : JDate) -> JString = "illusory0x0_core_Date" "toUTCString"
///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toGMTString)
