///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name)
pub fn Error_::name(self : Error_) -> String_ = "illusory0x0_core_global" "name"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/message)
pub fn Error_::message(self : Error_) -> String_ = "illusory0x0_core_global" "message"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/toString)
pub fn Error_::toString(self : Error_) -> String_ = "illusory0x0_core_Error" "toString"
