///|
pub extern type JAny

///|
pub extern type JObject

///|
pub extern type JArray[T]

///|
pub extern type JError

///|
pub extern type JAggregateError

///|
pub extern type JEvalError

///|
pub extern type JRangeError

///|
pub extern type JReferenceError

///|
pub extern type JSyntaxError

///|
pub extern type JTypeError

///|
pub extern type JURIError

///|
pub extern type JString

///|
pub extern type JTextDecoder

///|
pub extern type JTextEncoder

///|
pub extern type JTypedArray[T]

///|
pub extern type JArrayBuffer

///|
pub typealias JUint8Array = JTypedArray[Byte]

///|
pub typealias JUint16Array = JTypedArray[UInt16]

///|
pub typealias JUint32Array = JTypedArray[UInt]

///|
pub typealias JInt8Array = JTypedArray[Byte]

///|
pub typealias JInt16Array = JTypedArray[Int16]

///|
pub extern type JConsole

///|
pub typealias JInt32Array = JTypedArray[Int]

///|
pub typealias JFloat32Array = JTypedArray[Float]

///|
pub typealias JFloat64Array = JTypedArray[Double]

///|
pub typealias JBigInt64Array = JTypedArray[Int64]

///|
pub typealias JBigUint64Array = JTypedArray[UInt64]

///|
pub extern type JNumber

///|
pub extern type JDate

///|
pub extern type JRegExp

///|
pub extern type JMap[K, V]

///|
pub extern type JSet[V]

///|
pub extern type JWeakMap[K, V]

///|
pub extern type JWeakSet[V]

///|
pub extern type JSharedArrayBuffer

///|
pub extern type JDataView

///|
pub extern type JWeakRef[T]

///|
pub extern type JIterator[T]

// TODO
// pub extern type JFinalizationRegistry
// pub extern type JPromise[T]
