///|
pub impl Js_Object for JError with to_object(self) = "%identity"

///|
pub impl Js_Object for JAggregateError with to_object(self) = "%identity"

///|
pub impl Js_Object for JEvalError with to_object(self) = "%identity"

///|
pub impl Js_Object for JRangeError with to_object(self) = "%identity"

///|
pub impl Js_Object for JReferenceError with to_object(self) = "%identity"

///|
pub impl Js_Object for JSyntaxError with to_object(self) = "%identity"

///|
pub impl Js_Object for JTypeError with to_object(self) = "%identity"

///|
pub impl Js_Object for JTextEncoder with to_object(self) = "%identity"

///|
pub impl Js_Object for JObject with to_object(self) = "%identity"

///|
pub impl Js_Object for JString with to_object(self) = "%identity"

///|
pub impl Js_Object for JArrayBuffer with to_object(self) = "%identity"

///|
pub impl Js_Object for JConsole with to_object(self) = "%identity"

///|
pub impl[T] Js_Object for JTypedArray[T] with to_object(self) = "%identity"

///|
pub impl[T] Js_Object for JWeakSet[T] with to_object(self) = "%identity"

///|
pub impl[T] Js_Object for JSet[T] with to_object(self) = "%identity"

///|
pub impl[K, V] Js_Object for JMap[K, V] with to_object(self) = "%identity"

///|
pub impl[K, V] Js_Object for JWeakMap[K, V] with to_object(self) = "%identity"

///|
pub impl Js_Object for JDate with to_object(self) = "%identity"

///|
pub impl Js_Object for JRegExp with to_object(self) = "%identity"

///|
pub impl Js_Object for JSharedArrayBuffer with to_object(self) = "%identity"

///|
pub impl Js_Object for JDataView with to_object(self) = "%identity"

///|
pub impl[T] Js_Object for JWeakRef[T] with to_object(self) = "%identity"

///|
pub impl[T] Js_Object for JIterator[T] with to_object(self) = "%identity"

///|
pub impl[T] Js_Object for JArray[T] with to_object(self) = "%identity"
