///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/buffer)
pub fn JDataView::buffer(self : JDataView) -> JArrayBuffer = "DataView" "get_buffer"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/byteLength)
pub fn JDataView::byteLength(self : JDataView) -> Int = "DataView" "get_byteLength"

///| [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/byteOffset)
pub fn JDataView::byteOffset(self : JDataView) -> Int = "DataView" "get_byteOffset"
